// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.20.3
// source: gaming/service/v1/gaming.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateGameInstanceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId int64  `protobuf:"varint,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	Game   string `protobuf:"bytes,2,opt,name=game,proto3" json:"game,omitempty"`
}

func (x *CreateGameInstanceRequest) Reset() {
	*x = CreateGameInstanceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gaming_service_v1_gaming_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateGameInstanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGameInstanceRequest) ProtoMessage() {}

func (x *CreateGameInstanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gaming_service_v1_gaming_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGameInstanceRequest.ProtoReflect.Descriptor instead.
func (*CreateGameInstanceRequest) Descriptor() ([]byte, []int) {
	return file_gaming_service_v1_gaming_proto_rawDescGZIP(), []int{0}
}

func (x *CreateGameInstanceRequest) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *CreateGameInstanceRequest) GetGame() string {
	if x != nil {
		return x.Game
	}
	return ""
}

type CreateGameInstanceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId int64 `protobuf:"varint,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
}

func (x *CreateGameInstanceResponse) Reset() {
	*x = CreateGameInstanceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gaming_service_v1_gaming_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateGameInstanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGameInstanceResponse) ProtoMessage() {}

func (x *CreateGameInstanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gaming_service_v1_gaming_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGameInstanceResponse.ProtoReflect.Descriptor instead.
func (*CreateGameInstanceResponse) Descriptor() ([]byte, []int) {
	return file_gaming_service_v1_gaming_proto_rawDescGZIP(), []int{1}
}

func (x *CreateGameInstanceResponse) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

type OpenGameConnectionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId int64  `protobuf:"varint,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	UserId int64  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	Game   string `protobuf:"bytes,3,opt,name=game,proto3" json:"game,omitempty"`
	Token  string `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *OpenGameConnectionRequest) Reset() {
	*x = OpenGameConnectionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gaming_service_v1_gaming_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpenGameConnectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenGameConnectionRequest) ProtoMessage() {}

func (x *OpenGameConnectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gaming_service_v1_gaming_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenGameConnectionRequest.ProtoReflect.Descriptor instead.
func (*OpenGameConnectionRequest) Descriptor() ([]byte, []int) {
	return file_gaming_service_v1_gaming_proto_rawDescGZIP(), []int{2}
}

func (x *OpenGameConnectionRequest) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *OpenGameConnectionRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *OpenGameConnectionRequest) GetGame() string {
	if x != nil {
		return x.Game
	}
	return ""
}

func (x *OpenGameConnectionRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type OpenGameConnectionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId   int64  `protobuf:"varint,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	UserId   int64  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	SdpOffer string `protobuf:"bytes,3,opt,name=sdpOffer,proto3" json:"sdpOffer,omitempty"`
}

func (x *OpenGameConnectionResponse) Reset() {
	*x = OpenGameConnectionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gaming_service_v1_gaming_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpenGameConnectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenGameConnectionResponse) ProtoMessage() {}

func (x *OpenGameConnectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gaming_service_v1_gaming_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenGameConnectionResponse.ProtoReflect.Descriptor instead.
func (*OpenGameConnectionResponse) Descriptor() ([]byte, []int) {
	return file_gaming_service_v1_gaming_proto_rawDescGZIP(), []int{3}
}

func (x *OpenGameConnectionResponse) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *OpenGameConnectionResponse) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *OpenGameConnectionResponse) GetSdpOffer() string {
	if x != nil {
		return x.SdpOffer
	}
	return ""
}

type SDPAnswerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId    int64  `protobuf:"varint,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	UserId    int64  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	SdpAnswer string `protobuf:"bytes,3,opt,name=sdpAnswer,proto3" json:"sdpAnswer,omitempty"`
}

func (x *SDPAnswerRequest) Reset() {
	*x = SDPAnswerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gaming_service_v1_gaming_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SDPAnswerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SDPAnswerRequest) ProtoMessage() {}

func (x *SDPAnswerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gaming_service_v1_gaming_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SDPAnswerRequest.ProtoReflect.Descriptor instead.
func (*SDPAnswerRequest) Descriptor() ([]byte, []int) {
	return file_gaming_service_v1_gaming_proto_rawDescGZIP(), []int{4}
}

func (x *SDPAnswerRequest) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *SDPAnswerRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SDPAnswerRequest) GetSdpAnswer() string {
	if x != nil {
		return x.SdpAnswer
	}
	return ""
}

type SDPAnswerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId int64 `protobuf:"varint,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	UserId int64 `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (x *SDPAnswerResponse) Reset() {
	*x = SDPAnswerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gaming_service_v1_gaming_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SDPAnswerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SDPAnswerResponse) ProtoMessage() {}

func (x *SDPAnswerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gaming_service_v1_gaming_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SDPAnswerResponse.ProtoReflect.Descriptor instead.
func (*SDPAnswerResponse) Descriptor() ([]byte, []int) {
	return file_gaming_service_v1_gaming_proto_rawDescGZIP(), []int{5}
}

func (x *SDPAnswerResponse) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *SDPAnswerResponse) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type ICECandidateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId    int64  `protobuf:"varint,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	UserId    int64  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	Candidate string `protobuf:"bytes,3,opt,name=candidate,proto3" json:"candidate,omitempty"`
}

func (x *ICECandidateRequest) Reset() {
	*x = ICECandidateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gaming_service_v1_gaming_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ICECandidateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ICECandidateRequest) ProtoMessage() {}

func (x *ICECandidateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gaming_service_v1_gaming_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ICECandidateRequest.ProtoReflect.Descriptor instead.
func (*ICECandidateRequest) Descriptor() ([]byte, []int) {
	return file_gaming_service_v1_gaming_proto_rawDescGZIP(), []int{6}
}

func (x *ICECandidateRequest) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *ICECandidateRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ICECandidateRequest) GetCandidate() string {
	if x != nil {
		return x.Candidate
	}
	return ""
}

type ICECandidateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId int64 `protobuf:"varint,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	UserId int64 `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (x *ICECandidateResponse) Reset() {
	*x = ICECandidateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gaming_service_v1_gaming_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ICECandidateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ICECandidateResponse) ProtoMessage() {}

func (x *ICECandidateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gaming_service_v1_gaming_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ICECandidateResponse.ProtoReflect.Descriptor instead.
func (*ICECandidateResponse) Descriptor() ([]byte, []int) {
	return file_gaming_service_v1_gaming_proto_rawDescGZIP(), []int{7}
}

func (x *ICECandidateResponse) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *ICECandidateResponse) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type PauseEmulatorRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId int64 `protobuf:"varint,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	UserId int64 `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (x *PauseEmulatorRequest) Reset() {
	*x = PauseEmulatorRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gaming_service_v1_gaming_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PauseEmulatorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PauseEmulatorRequest) ProtoMessage() {}

func (x *PauseEmulatorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gaming_service_v1_gaming_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PauseEmulatorRequest.ProtoReflect.Descriptor instead.
func (*PauseEmulatorRequest) Descriptor() ([]byte, []int) {
	return file_gaming_service_v1_gaming_proto_rawDescGZIP(), []int{8}
}

func (x *PauseEmulatorRequest) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *PauseEmulatorRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type PauseEmulatorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId int64 `protobuf:"varint,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	UserId int64 `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (x *PauseEmulatorResponse) Reset() {
	*x = PauseEmulatorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gaming_service_v1_gaming_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PauseEmulatorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PauseEmulatorResponse) ProtoMessage() {}

func (x *PauseEmulatorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gaming_service_v1_gaming_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PauseEmulatorResponse.ProtoReflect.Descriptor instead.
func (*PauseEmulatorResponse) Descriptor() ([]byte, []int) {
	return file_gaming_service_v1_gaming_proto_rawDescGZIP(), []int{9}
}

func (x *PauseEmulatorResponse) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *PauseEmulatorResponse) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type RestartEmulatorRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId int64  `protobuf:"varint,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	UserId int64  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	Game   string `protobuf:"bytes,3,opt,name=game,proto3" json:"game,omitempty"`
}

func (x *RestartEmulatorRequest) Reset() {
	*x = RestartEmulatorRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gaming_service_v1_gaming_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RestartEmulatorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestartEmulatorRequest) ProtoMessage() {}

func (x *RestartEmulatorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gaming_service_v1_gaming_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestartEmulatorRequest.ProtoReflect.Descriptor instead.
func (*RestartEmulatorRequest) Descriptor() ([]byte, []int) {
	return file_gaming_service_v1_gaming_proto_rawDescGZIP(), []int{10}
}

func (x *RestartEmulatorRequest) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *RestartEmulatorRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RestartEmulatorRequest) GetGame() string {
	if x != nil {
		return x.Game
	}
	return ""
}

type RestartEmulatorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId int64 `protobuf:"varint,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	UserId int64 `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (x *RestartEmulatorResponse) Reset() {
	*x = RestartEmulatorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gaming_service_v1_gaming_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RestartEmulatorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestartEmulatorResponse) ProtoMessage() {}

func (x *RestartEmulatorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gaming_service_v1_gaming_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestartEmulatorResponse.ProtoReflect.Descriptor instead.
func (*RestartEmulatorResponse) Descriptor() ([]byte, []int) {
	return file_gaming_service_v1_gaming_proto_rawDescGZIP(), []int{11}
}

func (x *RestartEmulatorResponse) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *RestartEmulatorResponse) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

var File_gaming_service_v1_gaming_proto protoreflect.FileDescriptor

var file_gaming_service_v1_gaming_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x67, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2f, 0x76, 0x31, 0x2f, 0x67, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x09, 0x67, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x2e, 0x76, 0x31, 0x1a, 0x1c, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x47, 0x0a, 0x19, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x47, 0x61, 0x6d, 0x65, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x67, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x67, 0x61,
	0x6d, 0x65, 0x22, 0x34, 0x0a, 0x1a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x61, 0x6d, 0x65,
	0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x22, 0x75, 0x0a, 0x19, 0x4f, 0x70, 0x65, 0x6e,
	0x47, 0x61, 0x6d, 0x65, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x16, 0x0a,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x67, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x67, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22,
	0x68, 0x0a, 0x1a, 0x4f, 0x70, 0x65, 0x6e, 0x47, 0x61, 0x6d, 0x65, 0x43, 0x6f, 0x6e, 0x6e, 0x65,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x72,
	0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1a, 0x0a,
	0x08, 0x73, 0x64, 0x70, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x73, 0x64, 0x70, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x22, 0x60, 0x0a, 0x10, 0x53, 0x44, 0x50,
	0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a,
	0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x72,
	0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1c, 0x0a,
	0x09, 0x73, 0x64, 0x70, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x73, 0x64, 0x70, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x22, 0x43, 0x0a, 0x11, 0x53,
	0x44, 0x50, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x22, 0x63, 0x0a, 0x13, 0x49, 0x43, 0x45, 0x43, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12,
	0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x61, 0x6e, 0x64, 0x69,
	0x64, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x61, 0x6e, 0x64,
	0x69, 0x64, 0x61, 0x74, 0x65, 0x22, 0x46, 0x0a, 0x14, 0x49, 0x43, 0x45, 0x43, 0x61, 0x6e, 0x64,
	0x69, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x72,
	0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x46, 0x0a,
	0x14, 0x50, 0x61, 0x75, 0x73, 0x65, 0x45, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x16, 0x0a,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x47, 0x0a, 0x15, 0x50, 0x61, 0x75, 0x73, 0x65, 0x45, 0x6d,
	0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06,
	0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x5c,
	0x0a, 0x16, 0x52, 0x65, 0x73, 0x74, 0x61, 0x72, 0x74, 0x45, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x6f,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6f, 0x6d,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64,
	0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x67, 0x61, 0x6d, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x67, 0x61, 0x6d, 0x65, 0x22, 0x49, 0x0a, 0x17,
	0x52, 0x65, 0x73, 0x74, 0x61, 0x72, 0x74, 0x45, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12,
	0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x32, 0xa1, 0x04, 0x0a, 0x06, 0x47, 0x61, 0x6d, 0x69,
	0x6e, 0x67, 0x12, 0x63, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x61, 0x6d, 0x65,
	0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x24, 0x2e, 0x67, 0x61, 0x6d, 0x69, 0x6e,
	0x67, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x61, 0x6d, 0x65, 0x49,
	0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25,
	0x2e, 0x67, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x47, 0x61, 0x6d, 0x65, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x63, 0x0a, 0x12, 0x4f, 0x70, 0x65, 0x6e, 0x47,
	0x61, 0x6d, 0x65, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x24, 0x2e,
	0x67, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x2e, 0x76, 0x31, 0x2e, 0x4f, 0x70, 0x65, 0x6e, 0x47, 0x61,
	0x6d, 0x65, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x67, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x2e, 0x76, 0x31, 0x2e,
	0x4f, 0x70, 0x65, 0x6e, 0x47, 0x61, 0x6d, 0x65, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x48, 0x0a, 0x09,
	0x53, 0x44, 0x50, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x12, 0x1b, 0x2e, 0x67, 0x61, 0x6d, 0x69,
	0x6e, 0x67, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x44, 0x50, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x67, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x2e,
	0x76, 0x31, 0x2e, 0x53, 0x44, 0x50, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x51, 0x0a, 0x0c, 0x49, 0x43, 0x45, 0x43, 0x61, 0x6e,
	0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x12, 0x1e, 0x2e, 0x67, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x2e,
	0x76, 0x31, 0x2e, 0x49, 0x43, 0x45, 0x43, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x67, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x2e,
	0x76, 0x31, 0x2e, 0x49, 0x43, 0x45, 0x43, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x54, 0x0a, 0x0d, 0x50, 0x61, 0x75,
	0x73, 0x65, 0x45, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x1f, 0x2e, 0x67, 0x61, 0x6d,
	0x69, 0x6e, 0x67, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x61, 0x75, 0x73, 0x65, 0x45, 0x6d, 0x75, 0x6c,
	0x61, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x67, 0x61,
	0x6d, 0x69, 0x6e, 0x67, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x61, 0x75, 0x73, 0x65, 0x45, 0x6d, 0x75,
	0x6c, 0x61, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x5a, 0x0a, 0x0f, 0x52, 0x65, 0x73, 0x74, 0x61, 0x72, 0x74, 0x45, 0x6d, 0x75, 0x6c, 0x61, 0x74,
	0x6f, 0x72, 0x12, 0x21, 0x2e, 0x67, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x2e, 0x76, 0x31, 0x2e, 0x52,
	0x65, 0x73, 0x74, 0x61, 0x72, 0x74, 0x45, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x67, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x2e, 0x76,
	0x31, 0x2e, 0x52, 0x65, 0x73, 0x74, 0x61, 0x72, 0x74, 0x45, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x6f,
	0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x22, 0x5a, 0x20, 0x62,
	0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x67, 0x61, 0x6d, 0x69, 0x6e,
	0x67, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_gaming_service_v1_gaming_proto_rawDescOnce sync.Once
	file_gaming_service_v1_gaming_proto_rawDescData = file_gaming_service_v1_gaming_proto_rawDesc
)

func file_gaming_service_v1_gaming_proto_rawDescGZIP() []byte {
	file_gaming_service_v1_gaming_proto_rawDescOnce.Do(func() {
		file_gaming_service_v1_gaming_proto_rawDescData = protoimpl.X.CompressGZIP(file_gaming_service_v1_gaming_proto_rawDescData)
	})
	return file_gaming_service_v1_gaming_proto_rawDescData
}

var file_gaming_service_v1_gaming_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_gaming_service_v1_gaming_proto_goTypes = []any{
	(*CreateGameInstanceRequest)(nil),  // 0: gaming.v1.CreateGameInstanceRequest
	(*CreateGameInstanceResponse)(nil), // 1: gaming.v1.CreateGameInstanceResponse
	(*OpenGameConnectionRequest)(nil),  // 2: gaming.v1.OpenGameConnectionRequest
	(*OpenGameConnectionResponse)(nil), // 3: gaming.v1.OpenGameConnectionResponse
	(*SDPAnswerRequest)(nil),           // 4: gaming.v1.SDPAnswerRequest
	(*SDPAnswerResponse)(nil),          // 5: gaming.v1.SDPAnswerResponse
	(*ICECandidateRequest)(nil),        // 6: gaming.v1.ICECandidateRequest
	(*ICECandidateResponse)(nil),       // 7: gaming.v1.ICECandidateResponse
	(*PauseEmulatorRequest)(nil),       // 8: gaming.v1.PauseEmulatorRequest
	(*PauseEmulatorResponse)(nil),      // 9: gaming.v1.PauseEmulatorResponse
	(*RestartEmulatorRequest)(nil),     // 10: gaming.v1.RestartEmulatorRequest
	(*RestartEmulatorResponse)(nil),    // 11: gaming.v1.RestartEmulatorResponse
}
var file_gaming_service_v1_gaming_proto_depIdxs = []int32{
	0,  // 0: gaming.v1.Gaming.CreateGameInstance:input_type -> gaming.v1.CreateGameInstanceRequest
	2,  // 1: gaming.v1.Gaming.OpenGameConnection:input_type -> gaming.v1.OpenGameConnectionRequest
	4,  // 2: gaming.v1.Gaming.SDPAnswer:input_type -> gaming.v1.SDPAnswerRequest
	6,  // 3: gaming.v1.Gaming.ICECandidate:input_type -> gaming.v1.ICECandidateRequest
	8,  // 4: gaming.v1.Gaming.PauseEmulator:input_type -> gaming.v1.PauseEmulatorRequest
	10, // 5: gaming.v1.Gaming.RestartEmulator:input_type -> gaming.v1.RestartEmulatorRequest
	1,  // 6: gaming.v1.Gaming.CreateGameInstance:output_type -> gaming.v1.CreateGameInstanceResponse
	3,  // 7: gaming.v1.Gaming.OpenGameConnection:output_type -> gaming.v1.OpenGameConnectionResponse
	5,  // 8: gaming.v1.Gaming.SDPAnswer:output_type -> gaming.v1.SDPAnswerResponse
	7,  // 9: gaming.v1.Gaming.ICECandidate:output_type -> gaming.v1.ICECandidateResponse
	9,  // 10: gaming.v1.Gaming.PauseEmulator:output_type -> gaming.v1.PauseEmulatorResponse
	11, // 11: gaming.v1.Gaming.RestartEmulator:output_type -> gaming.v1.RestartEmulatorResponse
	6,  // [6:12] is the sub-list for method output_type
	0,  // [0:6] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_gaming_service_v1_gaming_proto_init() }
func file_gaming_service_v1_gaming_proto_init() {
	if File_gaming_service_v1_gaming_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_gaming_service_v1_gaming_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*CreateGameInstanceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gaming_service_v1_gaming_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*CreateGameInstanceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gaming_service_v1_gaming_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*OpenGameConnectionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gaming_service_v1_gaming_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*OpenGameConnectionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gaming_service_v1_gaming_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*SDPAnswerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gaming_service_v1_gaming_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*SDPAnswerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gaming_service_v1_gaming_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*ICECandidateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gaming_service_v1_gaming_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*ICECandidateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gaming_service_v1_gaming_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*PauseEmulatorRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gaming_service_v1_gaming_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*PauseEmulatorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gaming_service_v1_gaming_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*RestartEmulatorRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gaming_service_v1_gaming_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*RestartEmulatorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gaming_service_v1_gaming_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gaming_service_v1_gaming_proto_goTypes,
		DependencyIndexes: file_gaming_service_v1_gaming_proto_depIdxs,
		MessageInfos:      file_gaming_service_v1_gaming_proto_msgTypes,
	}.Build()
	File_gaming_service_v1_gaming_proto = out.File
	file_gaming_service_v1_gaming_proto_rawDesc = nil
	file_gaming_service_v1_gaming_proto_goTypes = nil
	file_gaming_service_v1_gaming_proto_depIdxs = nil
}
