// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/stellarisJAY/nesgo/backend/app/user/internal/biz"
	"github.com/stellarisJAY/nesgo/backend/app/user/internal/conf"
	"github.com/stellarisJAY/nesgo/backend/app/user/internal/data"
	"github.com/stellarisJAY/nesgo/backend/app/user/internal/server"
	"github.com/stellarisJAY/nesgo/backend/app/user/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, registry *conf.Registry, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, confServer)
	if err != nil {
		return nil, nil, err
	}
	userRepo := data.NewUserRepo(dataData, logger)
	userUseCase := biz.NewUserUseCase(userRepo, logger)
	userKeyboardBindingRepo := data.NewUserKeyboardBindingRepo(dataData, logger)
	userKeyboardBindingUseCase := biz.NewUserKeyboardBindingUseCase(userKeyboardBindingRepo, logger)
	macroRepo := data.NewMacroRepo(dataData, logger)
	macroUseCase := biz.NewMacroUseCase(macroRepo, logger)
	userService := service.NewUserService(userUseCase, userKeyboardBindingUseCase, macroUseCase, logger)
	grpcServer := server.NewGRPCServer(confServer, userService, logger)
	client := server.NewEtcdClient(registry)
	registrar := server.NewRegistrar(client)
	app := newApp(logger, grpcServer, registrar)
	return app, func() {
		cleanup()
	}, nil
}
