// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/stellarisJAY/nesgo/backend/app/gaming/internal/biz"
	"github.com/stellarisJAY/nesgo/backend/app/gaming/internal/conf"
	"github.com/stellarisJAY/nesgo/backend/app/gaming/internal/data"
	"github.com/stellarisJAY/nesgo/backend/app/gaming/internal/server"
	"github.com/stellarisJAY/nesgo/backend/app/gaming/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, registry *conf.Registry, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(registry, logger)
	if err != nil {
		return nil, nil, err
	}
	roomSessionRepo := data.NewRoomSessionRepo(dataData, logger)
	roomSessionUseCase := biz.NewRoomSessionUseCase(roomSessionRepo, logger)
	gamingService := service.NewGamingService(roomSessionUseCase, logger)
	grpcServer := server.NewGRPCServer(confServer, gamingService)
	registrar := service.NewRegistrar(registry)
	app := newApp(logger, grpcServer, registrar)
	return app, func() {
		cleanup()
	}, nil
}
