server:
  http:
    addr: 0.0.0.0:8010
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9010
    timeout: 1s
data:
  database:
    driver: mysql
    source: root:12345678@tcp(localhost:3306)/nesgo?parseTime=True&loc=Local
  redis:
    addr: localhost:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
registry:
  etcd:
    endpoints:
      - localhost:2379